# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/window_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_view = QtWidgets.QLabel(self.centralwidget)
        self.image_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.image_view.setText("")
        self.image_view.setObjectName("image_view")
        self.verticalLayout.addWidget(self.image_view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.enable_signs_detection_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.enable_signs_detection_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enable_signs_detection_checkbox.setObjectName("enable_signs_detection_checkbox")
        self.horizontalLayout.addWidget(self.enable_signs_detection_checkbox, 0, QtCore.Qt.AlignHCenter)
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setEnabled(False)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.enable_road_marking_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.enable_road_marking_checkbox.setObjectName("enable_road_marking_checkbox")
        self.horizontalLayout.addWidget(self.enable_road_marking_checkbox, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.load_file_action = QtWidgets.QAction(MainWindow)
        self.load_file_action.setObjectName("load_file_action")
        self.quit_action = QtWidgets.QAction(MainWindow)
        self.quit_action.setObjectName("quit_action")
        self.start_pause_action = QtWidgets.QAction(MainWindow)
        self.start_pause_action.setObjectName("start_pause_action")
        self.camera_action = QtWidgets.QAction(MainWindow)
        self.camera_action.setObjectName("camera_action")
        self.menu.addAction(self.load_file_action)
        self.menu.addAction(self.camera_action)
        self.menu.addSeparator()
        self.menu.addAction(self.quit_action)
        self.menu_2.addAction(self.start_pause_action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Road Signs & Markup Detector"))
        self.enable_signs_detection_checkbox.setText(_translate("MainWindow", "Обнаружение дорожных знаков"))
        self.start_btn.setText(_translate("MainWindow", "Пуск"))
        self.enable_road_marking_checkbox.setText(_translate("MainWindow", "Обнаружение разметки"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Воспроизведение"))
        self.load_file_action.setText(_translate("MainWindow", "Загрузить"))
        self.load_file_action.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.quit_action.setText(_translate("MainWindow", "Выход"))
        self.quit_action.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.start_pause_action.setText(_translate("MainWindow", "Пуск/пауза"))
        self.start_pause_action.setShortcut(_translate("MainWindow", "Space"))
        self.camera_action.setText(_translate("MainWindow", "Камера"))
